(() => {
  "use strict";

  const CONFIG = window.APP_CONFIG || {};
  const API_URL = String(CONFIG.API_URL || "").trim();
  const HAS_API_URL = /^https:\/\/script\.google\.com\/macros\/s\/[^/]+\/(?:exec|dev)(?:\?.*)?$/.test(API_URL);
  const IS_DEMO = !HAS_API_URL && CONFIG.ENABLE_DEMO_MODE === true;
  const CONFIG_ERROR = !HAS_API_URL && !IS_DEMO;
  const STORAGE_KEY = "trip-cost-share-v6-demo";
  const ADMIN_TOKEN_KEY = "trip-cost-share-v6-admin-token";
  const REQUEST_TIMEOUT_MS = Math.max(8000, Number(CONFIG.REQUEST_TIMEOUT_MS || 20000));
  const EPSILON = 0.011;
  const state = { settings:{}, participants:[], receipts:[], expenseLines:[], expenseShares:[], apiVersion:"-" };
  let token = sessionStorage.getItem(ADMIN_TOKEN_KEY) || "";

  const CATEGORY_LABELS = { food:"ค่าอาหาร", beverage:"เครื่องดื่ม", alcohol:"เครื่องดื่มแอลกอฮอล์", lodging:"ที่พัก", activity:"กิจกรรม", transport:"การเดินทาง", shared:"ของใช้ส่วนกลาง", other:"อื่น ๆ" };
  const $ = (id) => document.getElementById(id);
  const el = {
    connection:$("adminConnectionBadge"), loginSection:$("adminLoginSection"), loginForm:$("adminLoginForm"), password:$("adminPassword"), adminApp:$("adminApp"), demoBanner:$("adminDemoBanner"), refresh:$("adminRefreshBtn"), logout:$("adminLogoutBtn"),
    participantCount:$("adminParticipantCount"), receiptCount:$("adminReceiptCount"), grandTotal:$("adminGrandTotal"), statusText:$("adminStatusText"), apiVersion:$("adminApiVersion"),
    settingsForm:$("adminSettingsForm"), eventName:$("adminEventName"), startDate:$("adminStartDate"), endDate:$("adminEndDate"), eventStatus:$("adminEventStatus"), settingsSubmit:$("adminSettingsSubmitBtn"), settingsFeedback:$("adminSettingsFeedback"),
    participantForm:$("adminParticipantForm"), participantId:$("adminParticipantId"), participantName:$("adminParticipantName"), attendance:$("adminAttendanceOptions"), lodging:$("adminLodgingOptions"), drinks:$("adminDrinksAlcohol"), active:$("adminParticipantActive"), participantSubmit:$("adminParticipantSubmitBtn"), participantCancel:$("adminParticipantCancelBtn"), participantTable:$("adminParticipantTableBody"),
    receiptForm:$("adminReceiptForm"), receiptId:$("adminReceiptId"), receiptDate:$("adminReceiptDate"), receiptMerchant:$("adminReceiptMerchant"), receiptTotal:$("adminReceiptTotal"), receiptImage:$("adminReceiptImage"), receiptNote:$("adminReceiptNote"), existingReceipt:$("adminExistingReceipt"), viewReceipt:$("adminViewReceiptBtn"), removeReceipt:$("adminRemoveReceipt"), addPayer:$("adminAddPayerBtn"), payerRows:$("adminPayerRows"), addLine:$("adminAddLineBtn"), lineRows:$("adminLineRows"), receiptValidation:$("adminReceiptValidation"), receiptSubmit:$("adminReceiptSubmitBtn"), receiptCancel:$("adminReceiptCancelBtn"), receiptTable:$("adminReceiptTableBody"), toast:$("toast")
  };

  const money=(v)=>new Intl.NumberFormat("th-TH",{style:"currency",currency:"THB",minimumFractionDigits:2}).format(Number(v||0));
  const round2=(v)=>Math.round((Number(v||0)+Number.EPSILON)*100)/100;
  const esc=(v)=>String(v??"").replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const uid=(prefix)=>`${prefix}_${globalThis.crypto?.randomUUID?crypto.randomUUID():`${Date.now()}_${Math.random().toString(16).slice(2)}`}`;
  const sleep=(ms)=>new Promise((r)=>setTimeout(r,ms));
  function parseIsoDate(value){const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(String(value||""));return m?new Date(Date.UTC(+m[1],+m[2]-1,+m[3],12)):null;}
  function isoFromDate(d){return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}-${String(d.getUTCDate()).padStart(2,"0")}`;}
  function dateLabel(v){const d=parseIsoDate(v);return d?d.toLocaleDateString("th-TH",{timeZone:"Asia/Bangkok",day:"numeric",month:"short",year:"numeric"}):"-";}
  function buildDateRange(start,end){const c=parseIsoDate(start),s=parseIsoDate(end),out=[];if(!c||!s)return out;while(c<=s&&out.length<31){out.push(isoFromDate(c));c.setUTCDate(c.getUTCDate()+1);}return out;}
  function buildNightRange(start,end){const dates=buildDateRange(start,end);return dates.slice(0,Math.max(0,dates.length-1));}
  function participant(id){return state.participants.find((p)=>p.id===id);}
  function showToast(message){el.toast.textContent=message;el.toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.toast.classList.remove("show"),3000);}
  function normalize(){["participants","receipts","expenseLines","expenseShares"].forEach((k)=>{if(!Array.isArray(state[k]))state[k]=[];});state.participants.forEach((p)=>{p.attendanceDates=Array.isArray(p.attendanceDates)?p.attendanceDates:[];p.lodgingNights=Array.isArray(p.lodgingNights)?p.lodgingNights:[];p.active=p.active!==false;});}
  function setBusy(form,busy,button,text){form?.querySelectorAll("input,select,button").forEach((n)=>{if(busy){n.dataset.wasDisabled=n.disabled?"1":"0";n.disabled=true;}else if(n.dataset.wasDisabled!=="1")n.disabled=false;if(!busy)delete n.dataset.wasDisabled;});if(button){if(busy){button.dataset.originalText=button.textContent;button.textContent=text||"กำลังบันทึก...";}else if(button.dataset.originalText){button.textContent=button.dataset.originalText;delete button.dataset.originalText;}}}

  async function fetchJson(url,options={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{const response=await fetch(url,{...options,signal:controller.signal,redirect:"follow",cache:"no-store"});const text=await response.text();let result;try{result=JSON.parse(text);}catch(_){throw new Error("เซิร์ฟเวอร์ตอบกลับไม่ใช่ JSON กรุณาตรวจ Deployment URL");}if(!result.ok){const error=new Error(result.message||"คำขอไม่สำเร็จ");error.code=result.code||"ERROR";throw error;}return result;}catch(error){if(error.name==="AbortError")throw new Error("เชื่อมต่อเซิร์ฟเวอร์นานเกินกำหนด");throw error;}finally{clearTimeout(timer);}}
  async function apiPost(action,payload={}){const delays=[0,350,800,1500];let last;for(const delay of delays){if(delay)await sleep(delay);try{return await fetchJson(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,payload,token})});}catch(error){last=error;if(error.code==="AUTH_REQUIRED"){logoutLocal();throw error;}if(error.code!=="BUSY")throw error;}}throw last||new Error("ระบบกำลังบันทึกข้อมูลอื่น");}

  function demoLoad(){try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)Object.assign(state,JSON.parse(raw));}catch(_){}normalize();state.apiVersion="demo";}
  function demoSave(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
  function demoLogin(password){if(password!=="Admin1234")throw new Error("รหัส Admin ไม่ถูกต้อง");token="demo-token";sessionStorage.setItem(ADMIN_TOKEN_KEY,token);demoLoad();}

  async function login(password){if(IS_DEMO){demoLogin(password);return;}const result=await fetchJson(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action:"adminLogin",payload:{password}})});token=result.data.token;sessionStorage.setItem(ADMIN_TOKEN_KEY,token);}
  async function bootstrap(fresh=false){if(IS_DEMO){demoLoad();return;}const result=await apiPost("adminBootstrap",{fresh});Object.assign(state,result.data);state.apiVersion=result.apiVersion||result.data.apiVersion||"6.0";normalize();}
  function logoutLocal(){token="";sessionStorage.removeItem(ADMIN_TOKEN_KEY);el.adminApp.classList.add("hidden");el.loginSection.classList.remove("hidden");el.refresh.classList.add("hidden");el.logout.classList.add("hidden");el.connection.textContent="รอเข้าสู่ระบบ";}
  async function logout(){try{if(!IS_DEMO&&token)await apiPost("adminLogout",{});}catch(_){}logoutLocal();}
  function showApp(){el.loginSection.classList.add("hidden");el.adminApp.classList.remove("hidden");el.refresh.classList.remove("hidden");el.logout.classList.remove("hidden");el.connection.textContent=IS_DEMO?"โหมดทดลอง":"เชื่อมต่อแล้ว";if(IS_DEMO)el.demoBanner.classList.remove("hidden");else el.demoBanner.classList.add("hidden");renderAll();}

  function renderOverview(){el.participantCount.textContent=state.participants.filter((p)=>p.active!==false).length;el.receiptCount.textContent=state.receipts.length;el.grandTotal.textContent=money(state.receipts.reduce((s,r)=>s+Number(r.total||0),0));el.statusText.textContent=String(state.settings.status||"open").toUpperCase();el.apiVersion.textContent=`API ${state.apiVersion||"6.0"}`;}
  function renderSettings(){el.eventName.value=state.settings.eventName||"Trip Cost Share";el.startDate.value=state.settings.startDate||"";el.endDate.value=state.settings.endDate||"";el.eventStatus.value=state.settings.status||"open";}
  function renderDateChecks(selectedAttendance=[],selectedLodging=[]){const dates=buildDateRange(state.settings.startDate,state.settings.endDate);const nights=buildNightRange(state.settings.startDate,state.settings.endDate);el.attendance.innerHTML=dates.map((d)=>`<label class="choice-card"><input type="checkbox" value="${esc(d)}" ${selectedAttendance.includes(d)?"checked":""}><span>${esc(dateLabel(d))}</span></label>`).join("")||`<span class="field-hint">ยังไม่ได้ตั้งช่วงวันที่</span>`;el.lodging.innerHTML=nights.map((d)=>`<label class="choice-card"><input type="checkbox" value="${esc(d)}" ${selectedLodging.includes(d)?"checked":""}><span>คืน ${esc(dateLabel(d))}</span></label>`).join("")||`<span class="field-hint">ไม่มีคืนพัก</span>`;}
  function renderParticipants(){el.participantTable.innerHTML=state.participants.length?state.participants.map((p)=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${p.attendanceDates.map(dateLabel).join(", ")||"-"}</td><td>${p.lodgingNights.map((d)=>`คืน ${dateLabel(d)}`).join(", ")||"-"}</td><td>${p.active===false?"ปิดใช้งาน":p.drinksAlcohol?"ใช้งาน · ดื่ม":"ใช้งาน · ไม่ดื่ม"}</td><td class="right"><button class="btn secondary" data-edit-person="${esc(p.id)}" type="button">แก้ไข</button> <button class="btn danger" data-delete-person="${esc(p.id)}" type="button">ลบ</button></td></tr>`).join(""):`<tr><td colspan="5" class="empty-cell">ยังไม่มีรายชื่อ</td></tr>`;el.participantTable.querySelectorAll("[data-edit-person]").forEach((b)=>b.addEventListener("click",()=>editParticipant(b.dataset.editPerson)));el.participantTable.querySelectorAll("[data-delete-person]").forEach((b)=>b.addEventListener("click",()=>deleteParticipant(b.dataset.deletePerson)));}
  function resetParticipant(){el.participantForm.reset();el.participantId.value="";el.active.checked=true;if(el.drinks)el.drinks.checked=false;renderDateChecks();el.participantSubmit.textContent="เพิ่มรายชื่อ";el.participantCancel.classList.add("hidden");}
  function editParticipant(id){const p=participant(id);if(!p)return;el.participantId.value=p.id;el.participantName.value=p.name;el.active.checked=p.active!==false;if(el.drinks)el.drinks.checked=Boolean(p.drinksAlcohol);renderDateChecks(p.attendanceDates,p.lodgingNights);el.participantSubmit.textContent="บันทึกการแก้ไข";el.participantCancel.classList.remove("hidden");el.participantForm.scrollIntoView({block:"start"});}
  async function deleteParticipant(id){if(!confirm("ยืนยันการลบรายชื่อนี้หรือไม่?"))return;try{if(IS_DEMO){state.participants=state.participants.filter((p)=>p.id!==id);demoSave();}else await apiPost("adminDeleteParticipant",{id});state.participants=state.participants.filter((p)=>p.id!==id);renderAll();showToast("ลบรายชื่อแล้ว");}catch(error){showToast(error.message);}}

  function allParticipantOptions(selected=""){return `<option value="">เลือกรายชื่อ</option>${state.participants.map((p)=>`<option value="${esc(p.id)}" ${p.id===selected?"selected":""}>${esc(p.name)}${p.active===false?" (ปิดใช้งาน)":""}</option>`).join("")}`;}
  function addPayerRow(data={}){const fragment=$("adminPayerRowTemplate").content.cloneNode(true),row=fragment.querySelector(".payer-row");row.querySelector(".payer-person").innerHTML=allParticipantOptions(data.participantId||"");row.querySelector(".payer-amount").value=data.amount||"";row.querySelector(".remove-row-btn").addEventListener("click",()=>{if(el.payerRows.children.length<=1)return showToast("ต้องมีผู้จ่ายอย่างน้อย 1 คน");row.remove();});el.payerRows.appendChild(fragment);}
  function shareOption(p,mode,selected,values){const checked=selected.includes(p.id),needs=mode==="weighted"||mode==="manual",value=values[p.id]??(mode==="weighted"?1:"");return `<label class="share-option"><span class="share-option-main"><input class="share-person-check" type="checkbox" value="${esc(p.id)}" ${checked?"checked":""}><span>${esc(p.name)}</span></span>${needs?`<span class="share-value"><small>${mode==="manual"?"บาท":"หน่วย"}</small><input class="share-person-value" data-person-id="${esc(p.id)}" type="number" min="0" step="0.01" value="${esc(value)}" ${checked?"":"disabled"}></span>`:""}</label>`;}
  function candidatePeople(card){const mode=card.querySelector(".line-split-mode").value,category=card.querySelector(".line-category").value,service=card.querySelector(".line-service-date").value||el.receiptDate.value;let rows=state.participants;if(mode==="attendance_date")rows=rows.filter((p)=>p.attendanceDates.includes(el.receiptDate.value));if(mode==="lodging_night")rows=rows.filter((p)=>p.lodgingNights.includes(service));if(category==="alcohol")rows=rows.filter((p)=>p.drinksAlcohol===true);return rows;}
  function collectSelection(card){const ids=[...card.querySelectorAll(".share-person-check:checked")].map((x)=>x.value),values={};card.querySelectorAll(".share-person-value").forEach((x)=>{if(ids.includes(x.dataset.personId))values[x.dataset.personId]=Number(x.value||0);});return{ids,values};}
  function renderLinePeople(card,preserve=true,source={}){const mode=card.querySelector(".line-split-mode").value,candidates=candidatePeople(card);const prior=preserve?collectSelection(card):{ids:source.selectedParticipantIds||candidates.map((p)=>p.id),values:mode==="manual"?(source.manualShares||{}):(source.weights||{})};let ids=mode==="all_equal"?candidates.filter((p)=>p.active!==false).map((p)=>p.id):prior.ids;ids=ids.filter((id)=>candidates.some((p)=>p.id===id));const container=card.querySelector(".line-participant-options");container.innerHTML=candidates.map((p)=>shareOption(p,mode,ids,prior.values)).join("")||`<span class="field-hint">ไม่มีรายชื่อที่ตรงเงื่อนไข</span>`;container.querySelectorAll(".share-person-check").forEach((c)=>{if(mode==="all_equal")c.disabled=true;c.addEventListener("change",()=>{const input=container.querySelector(`.share-person-value[data-person-id="${CSS.escape(c.value)}"]`);if(input)input.disabled=!c.checked;});});}
  function updateLineUi(card){const mode=card.querySelector(".line-split-mode").value,field=card.querySelector(".line-service-date-field"),input=card.querySelector(".line-service-date");field.classList.toggle("hidden",mode!=="lodging_night");const nights=buildNightRange(state.settings.startDate,state.settings.endDate);if(mode==="lodging_night"&&!nights.includes(input.value))input.value=nights[0]||"";}
  function ensureLegacyCategory(select,value){if(value!=="alcohol"||select.querySelector('option[value="alcohol"]'))return;const option=document.createElement("option");option.value="alcohol";option.textContent="เครื่องดื่มแอลกอฮอล์";select.appendChild(option);}
  function addLine(data={}){const fragment=$("adminLineTemplate").content.cloneNode(true),card=fragment.querySelector(".line-card");card.dataset.lineId=data.id||uid("line");card.querySelector(".line-description").value=data.description||"";const categorySelect=card.querySelector(".line-category");ensureLegacyCategory(categorySelect,data.category);categorySelect.value=data.category||"food";card.querySelector(".line-amount").value=data.amount||"";card.querySelector(".line-split-mode").value=data.splitMode||"attendance_date";card.querySelector(".line-service-date").value=data.serviceDate||el.receiptDate.value;card.querySelector(".remove-line-btn").addEventListener("click",()=>{if(el.lineRows.children.length<=1)return showToast("ต้องมีรายการอย่างน้อย 1 รายการ");card.remove();renumberLines();});card.querySelector(".line-category").addEventListener("change",()=>renderLinePeople(card,false));card.querySelector(".line-split-mode").addEventListener("change",()=>{updateLineUi(card);renderLinePeople(card,false);});card.querySelector(".line-service-date").addEventListener("change",()=>renderLinePeople(card,false));el.lineRows.appendChild(fragment);updateLineUi(card);renderLinePeople(card,false,data);renumberLines();}
  function renumberLines(){[...el.lineRows.querySelectorAll(".line-card")].forEach((c,i)=>c.querySelector(".line-number").textContent=`รายการที่ ${i+1}`);}
  function collectLine(card){const mode=card.querySelector(".line-split-mode").value,sel=collectSelection(card);return{id:card.dataset.lineId||uid("line"),description:card.querySelector(".line-description").value.trim(),category:card.querySelector(".line-category").value,amount:round2(card.querySelector(".line-amount").value),splitMode:mode,serviceDate:mode==="lodging_night"?card.querySelector(".line-service-date").value:el.receiptDate.value,selectedParticipantIds:sel.ids,weights:mode==="weighted"?sel.values:{},manualShares:mode==="manual"?sel.values:{}};}
  function calculateAdminShares(line){const ids=[...(line.selectedParticipantIds||[])];if(!ids.length)return{};if(line.splitMode==="manual")return Object.fromEntries(ids.map((id)=>[id,round2(line.manualShares?.[id]||0)]));const weighted=ids.map((id)=>{let weight=1;if(line.splitMode==="person_days")weight=Math.max(1,participant(id)?.attendanceDates?.length||0);if(line.splitMode==="weighted")weight=Number(line.weights?.[id]||0);return{id,weight};}).filter((x)=>x.weight>0);const totalCents=Math.round(Number(line.amount||0)*100),totalWeight=weighted.reduce((s,x)=>s+x.weight,0);if(!totalWeight)return{};const rows=weighted.map((x)=>{const raw=totalCents*x.weight/totalWeight;return{id:x.id,cents:Math.floor(raw),remainder:raw-Math.floor(raw)};});let left=totalCents-rows.reduce((s,x)=>s+x.cents,0);rows.sort((a,b)=>b.remainder-a.remainder||a.id.localeCompare(b.id));for(let i=0;i<rows.length&&left>0;i++,left--)rows[i].cents++;return Object.fromEntries(rows.map((x)=>[x.id,x.cents/100]));}
  function validateReceipt(payload){const errors=[];if(!payload.date)errors.push("กรุณาระบุวันที่");if(!payload.merchant)errors.push("กรุณาระบุร้านค้า/ผู้ให้บริการ");if(!(payload.total>0))errors.push("ยอดรวมต้องมากกว่า 0");const payerTotal=round2(payload.payerContributions.reduce((s,p)=>s+p.amount,0));if(Math.abs(payerTotal-payload.total)>EPSILON)errors.push("ยอดผู้จ่ายรวมไม่ตรงกับยอดใบเสร็จ");const lineTotal=round2(payload.lines.reduce((s,l)=>s+l.amount,0));if(Math.abs(lineTotal-payload.total)>EPSILON)errors.push("ยอดรายการย่อยรวมไม่ตรงกับยอดใบเสร็จ");payload.lines.forEach((l,i)=>{if(!l.description||!(l.amount>0)||!l.selectedParticipantIds.length)errors.push(`รายการที่ ${i+1} ยังไม่ครบ`);if(l.splitMode==="manual"){const manual=round2(l.selectedParticipantIds.reduce((s,id)=>s+Number(l.manualShares[id]||0),0));if(Math.abs(manual-l.amount)>EPSILON)errors.push(`ยอดรายบุคคลของรายการที่ ${i+1} ไม่ตรงกับยอดรายการ`);}});return errors;}
  async function resizeReceipt(file){if(!file)return null;if(!/^image\/(jpeg|png|webp)$/.test(file.type))throw new Error("รองรับเฉพาะ JPG, PNG หรือ WebP");const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});const img=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=data;});const max=Number(CONFIG.RECEIPT_MAX_WIDTH||1280),scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height);return{name:(file.name||"receipt.jpg").replace(/\.[^.]+$/,"")+".jpg",mimeType:"image/jpeg",dataBase64:canvas.toDataURL("image/jpeg",Number(CONFIG.RECEIPT_JPEG_QUALITY||.76)).split(",")[1]};}
  function receiptLines(id){return state.expenseLines.filter((l)=>l.receiptId===id);}
  function renderReceipts(){const lineCounts=new Map();state.expenseLines.forEach((line)=>lineCounts.set(line.receiptId,(lineCounts.get(line.receiptId)||0)+1));el.receiptTable.innerHTML=state.receipts.length?[...state.receipts].sort((a,b)=>String(b.date).localeCompare(String(a.date))).map((r)=>`<tr><td>${esc(dateLabel(r.date))}</td><td><strong>${esc(r.merchant)}</strong></td><td>${lineCounts.get(r.id)||0}</td><td>${r.receiptUrl?`<a href="${esc(r.receiptUrl)}" target="_blank" rel="noopener">ดูรูป</a>`:"-"}</td><td class="right"><strong>${money(r.total)}</strong></td><td class="right"><button class="btn secondary" data-edit-receipt="${esc(r.id)}" type="button">แก้ไข</button> <button class="btn danger" data-delete-receipt="${esc(r.id)}" type="button">ลบ</button></td></tr>`).join(""):`<tr><td colspan="6" class="empty-cell">ยังไม่มีใบเสร็จ</td></tr>`;el.receiptTable.querySelectorAll("[data-edit-receipt]").forEach((b)=>b.addEventListener("click",()=>editReceipt(b.dataset.editReceipt)));el.receiptTable.querySelectorAll("[data-delete-receipt]").forEach((b)=>b.addEventListener("click",()=>deleteReceipt(b.dataset.deleteReceipt)));}
  function resetReceipt(){el.receiptForm.reset();el.receiptId.value="";el.payerRows.innerHTML="";el.lineRows.innerHTML="";el.existingReceipt.classList.add("hidden");el.removeReceipt.checked=false;el.receiptValidation.classList.add("hidden");el.receiptCancel.classList.add("hidden");el.receiptSubmit.textContent="บันทึกการแก้ไข";}
  function editReceipt(id){const r=state.receipts.find((x)=>x.id===id);if(!r)return;resetReceipt();el.receiptId.value=r.id;el.receiptDate.value=r.date;el.receiptMerchant.value=r.merchant;el.receiptTotal.value=r.total;el.receiptNote.value=r.note||"";(r.payerContributions||[]).forEach(addPayerRow);receiptLines(id).forEach(addLine);if(r.receiptUrl){el.existingReceipt.classList.remove("hidden");el.viewReceipt.onclick=()=>window.open(r.receiptUrl,"_blank","noopener");}el.receiptCancel.classList.remove("hidden");el.receiptForm.scrollIntoView({block:"start"});}
  async function deleteReceipt(id){if(!confirm("ยืนยันการลบใบเสร็จนี้หรือไม่?"))return;try{if(IS_DEMO){state.receipts=state.receipts.filter((r)=>r.id!==id);state.expenseLines=state.expenseLines.filter((l)=>l.receiptId!==id);state.expenseShares=state.expenseShares.filter((s)=>s.receiptId!==id);demoSave();}else await apiPost("adminDeleteReceipt",{id});state.receipts=state.receipts.filter((r)=>r.id!==id);state.expenseLines=state.expenseLines.filter((l)=>l.receiptId!==id);state.expenseShares=state.expenseShares.filter((s)=>s.receiptId!==id);renderAll();showToast("ลบใบเสร็จแล้ว");}catch(error){showToast(error.message);}}
  function renderAll(){renderOverview();renderSettings();renderDateChecks();renderParticipants();renderReceipts();}

  el.loginForm.addEventListener("submit",async(e)=>{e.preventDefault();if(CONFIG_ERROR)return showToast("กรุณาตั้ง API_URL ใน config.js ก่อน");const button=e.submitter;setBusy(el.loginForm,true,button,"กำลังเข้าสู่ระบบ...");try{await login(el.password.value);await bootstrap(true);showApp();}catch(error){showToast(error.message);logoutLocal();}finally{setBusy(el.loginForm,false,button);}});
  el.logout.addEventListener("click",logout);el.refresh.addEventListener("click",async()=>{try{await bootstrap(true);renderAll();showToast("รีเฟรชข้อมูลแล้ว");}catch(error){showToast(error.message);}});
  el.settingsForm.addEventListener("submit",async(e)=>{e.preventDefault();const payload={eventName:el.eventName.value.trim(),startDate:el.startDate.value,endDate:el.endDate.value,status:el.eventStatus.value};setBusy(el.settingsForm,true,el.settingsSubmit,"กำลังบันทึก...");el.settingsFeedback.textContent="";try{if(IS_DEMO){state.settings={...state.settings,...payload};demoSave();}else{const result=await apiPost("adminSaveSettings",payload);state.settings=result.data.settings;}normalize();renderAll();el.settingsFeedback.textContent=`บันทึกสำเร็จ · ${dateLabel(state.settings.startDate)} – ${dateLabel(state.settings.endDate)}`;showToast("บันทึกกิจกรรมแล้ว");}catch(error){el.settingsFeedback.textContent=error.message;showToast(error.message);}finally{setBusy(el.settingsForm,false,el.settingsSubmit);}});
  el.participantCancel.addEventListener("click",resetParticipant);
  el.participantForm.addEventListener("submit",async(e)=>{e.preventDefault();const existing=participant(el.participantId.value);const payload={id:el.participantId.value||uid("p"),name:el.participantName.value.trim(),attendanceDates:[...el.attendance.querySelectorAll("input:checked")].map((x)=>x.value),lodgingNights:[...el.lodging.querySelectorAll("input:checked")].map((x)=>x.value),active:el.active.checked,drinksAlcohol:Boolean(el.drinks?.checked),createdAt:existing?.createdAt};setBusy(el.participantForm,true,el.participantSubmit,"กำลังบันทึก...");try{if(IS_DEMO){const idx=state.participants.findIndex((p)=>p.id===payload.id);const saved={...payload,createdAt:payload.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(idx>=0)state.participants[idx]=saved;else state.participants.push(saved);demoSave();}else{const result=await apiPost("adminSaveParticipant",payload);const saved=result.data.participant;const idx=state.participants.findIndex((p)=>p.id===saved.id);if(idx>=0)state.participants[idx]=saved;else state.participants.push(saved);}normalize();resetParticipant();renderAll();showToast("บันทึกรายชื่อแล้ว");}catch(error){showToast(error.message);}finally{setBusy(el.participantForm,false,el.participantSubmit);}});
  el.addPayer.addEventListener("click",()=>addPayerRow());el.addLine.addEventListener("click",()=>addLine());el.receiptCancel.addEventListener("click",resetReceipt);
  el.receiptForm.addEventListener("submit",async(e)=>{e.preventDefault();if(!el.receiptId.value)return showToast("กรุณากดแก้ไขจากตารางก่อน");const existing=state.receipts.find((r)=>r.id===el.receiptId.value);const payload={id:el.receiptId.value,date:el.receiptDate.value,merchant:el.receiptMerchant.value.trim(),total:round2(el.receiptTotal.value),note:el.receiptNote.value.trim(),payerContributions:[...el.payerRows.querySelectorAll(".payer-row")].map((row)=>({participantId:row.querySelector(".payer-person").value,amount:round2(row.querySelector(".payer-amount").value)})),lines:[...el.lineRows.querySelectorAll(".line-card")].map(collectLine),removeReceipt:el.removeReceipt.checked,createdAt:existing?.createdAt};const errors=validateReceipt(payload);el.receiptValidation.classList.toggle("hidden",!errors.length);el.receiptValidation.innerHTML=errors.length?`<strong>กรุณาตรวจสอบ:</strong><ul>${errors.map((x)=>`<li>${esc(x)}</li>`).join("")}</ul>`:"";if(errors.length)return;setBusy(el.receiptForm,true,el.receiptSubmit,"กำลังบันทึก...");try{payload.receiptImage=await resizeReceipt(el.receiptImage.files[0]);if(IS_DEMO){const now=new Date().toISOString();let receiptUrl=existing?.receiptUrl||"";if(payload.removeReceipt)receiptUrl="";if(payload.receiptImage?.dataBase64)receiptUrl=`data:${payload.receiptImage.mimeType};base64,${payload.receiptImage.dataBase64}`;const savedReceipt={...existing,...payload,receiptImage:undefined,receiptUrl,receiptThumbnailUrl:receiptUrl,updatedAt:now};state.receipts=state.receipts.filter((r)=>r.id!==payload.id);state.expenseLines=state.expenseLines.filter((l)=>l.receiptId!==payload.id);state.expenseShares=state.expenseShares.filter((s)=>s.receiptId!==payload.id);state.receipts.push(savedReceipt);payload.lines.forEach((line)=>{state.expenseLines.push({...line,receiptId:payload.id,createdAt:line.createdAt||now,updatedAt:now});const shares=calculateAdminShares(line);Object.entries(shares).forEach(([participantId,amount])=>state.expenseShares.push({id:uid("share"),receiptId:payload.id,lineId:line.id,participantId,amount,createdAt:now}));});demoSave();}else{const result=await apiPost("adminSaveReceipt",payload);state.receipts=state.receipts.filter((r)=>r.id!==payload.id);state.expenseLines=state.expenseLines.filter((l)=>l.receiptId!==payload.id);state.expenseShares=state.expenseShares.filter((s)=>s.receiptId!==payload.id);state.receipts.push(result.data.receipt);state.expenseLines.push(...result.data.expenseLines);state.expenseShares.push(...result.data.expenseShares);}resetReceipt();renderAll();showToast("บันทึกการแก้ไขแล้ว");}catch(error){showToast(error.message);}finally{setBusy(el.receiptForm,false,el.receiptSubmit);}});

  resetParticipant();resetReceipt();
  if (CONFIG_ERROR) {
    el.connection.textContent = "ยังไม่ได้ตั้ง API URL";
    el.demoBanner.classList.remove("hidden");
    el.demoBanner.innerHTML = "<strong>ยังไม่ได้เชื่อม Google Sheet:</strong> กรุณาใส่ Web App URL จริงใน config.js ก่อนใช้งาน Admin";
    el.loginForm.querySelectorAll("input,button").forEach((node)=>node.disabled=true);
  } else if(token){bootstrap(false).then(()=>showApp()).catch(()=>logoutLocal());}
})();
