window.APP_CONFIG = {
  APP_NAME: "Trip Cost Share",
  API_URL: "https://script.google.com/macros/s/AKfycbwgiyT38oQE29YZGWrE49oUUwh6sJVCrvhyF7RnFZ4-DQ-JBnS4Fp2smfqH5gH83jvBEw/exec",
  RECEIPT_MAX_WIDTH: 1280,
  RECEIPT_JPEG_QUALITY: 0.76,
  REQUEST_TIMEOUT_MS: 20000,
  SNAPSHOT_MAX_AGE_MINUTES: 30
};
